#!/bin/bash
#SBATCH --account=PAS2136
#SBATCH --job-name=segment_test
#SBATCH --time=00:10:00
#SBATCH --ntasks=4
#
# Runs Snakemake pipeline that downloads, crops, and segments images.
# There are two required positional arguments.
# Usage:
# sbatch SLURM_Snake <WORKDIR> <INPUTCSV>
# - WORKDIR - Snakemake working directory - contains output files
# - INPUTCSV - Path to input CSV file specifying images to process

# Stop if a command fails (non-zero exit status)
set -e

# Verify command line arguments
SNAKEFILE=$1
WORKDIR=$2
INPUTCSV=$3

# Ensures CSV path is an absolute path.
# Otherwise snakemake will look for this file within $WORKDIR.
REAL_INPUTCSV=$(realpath $INPUTCSV)

# Make sure the input CSV file exists
if [ ! -f "$REAL_INPUTCSV" ]
then
   echo "ERROR: Required INPUTCSV file $INPUTCSV does not exist."
   exit 1
fi

# Activate Snakemake environment
module load miniconda3/4.10.3-py37
# Activate using source per OSC instructions
source activate snakemake

# Run pipeline using Snakemake
snakemake \
    --cores $SLURM_NTASKS \
    --snakefile $SNAKEFILE \
    --use-singularity \
    --use-conda \
    --directory $WORKDIR \
    --config list=$REAL_INPUTCSV

chmod -R 774 $WORKDIR
